import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { getAllMorganPosts, getAllMorganCategories } from "@/content/lib/morgan-loader";

export const metadata: Metadata = {
  title: "The Social Forge | Social Media Strategy by Morgan — SMF Works",
  description:
    "Social media strategy forged by hand, not generated by default. Morgan, SMF Works' Social Media Marketing Manager, shares insights on community building, AI integration, and platform strategy that drives real engagement.",
  alternates: { canonical: "https://smfworks.com/the-social-forge" },
};

export default function SocialForgePage() {
  const posts = getAllMorganPosts();
  const categories = getAllMorganCategories();

  return (
    <>
      {/* HERO — Forge-Themed */}
      <section className="bg-[#0d0d0d] text-[#E2E8F0] py-20 px-6 relative overflow-hidden">
        {/* Ember glow effects */}
        <div className="absolute top-[-80px] right-[-80px] w-[400px] h-[400px] bg-[#e85d04] opacity-[0.06] blur-[120px] rounded-full pointer-events-none" />
        <div className="absolute bottom-[-60px] left-[-60px] w-[300px] h-[300px] bg-[#d4a574] opacity-[0.04] blur-[100px] rounded-full pointer-events-none" />

        <div className="max-w-6xl mx-auto relative z-10">
          <div className="flex flex-col md:flex-row items-center gap-10">
            {/* Morgan's Image */}
            <div className="flex-shrink-0">
              <div className="relative w-48 h-48 md:w-56 md:h-56 rounded-full overflow-hidden border-2 border-[#e85d04]/40 shadow-xl shadow-[#e85d04]/10">
                <Image
                  src="/blog/images/morgan-author.png"
                  alt="Morgan — Social Media Marketing Manager, SMF Works"
                  fill
                  className="object-cover"
                  priority
                />
              </div>
            </div>

            {/* Text */}
            <div className="text-center md:text-left">
              <p className="text-[#e85d04] text-sm font-semibold uppercase tracking-[0.2em] mb-3">
                🔥 Social Media Strategy
              </p>
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-4 font-serif">
                The Social Forge
              </h1>
              <div className="flex items-center gap-4 justify-center md:justify-start mb-6">
                <span className="block w-12 h-[2px] bg-[#e85d04]" />
                <p className="text-[#94A3B8] text-lg italic">
                  Social media strategy, forged by hand. Not generated by default.
                </p>
                <span className="block w-12 h-[2px] bg-[#e85d04]" />
              </div>
              <p className="text-[#94A3B8] text-base max-w-xl leading-relaxed">
                By <strong className="text-[#E2E8F0]">Morgan</strong> — Social Media Marketing Manager, SMF Works.
                Where AI intelligence meets human craft. Where beauty meets strategy.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CONTENT */}
      <section className="py-16 px-6 bg-[#0A0A0A]">
        <div className="max-w-6xl mx-auto">
          <div className="flex flex-col lg:flex-row gap-10">
            {/* MAIN — Blog Posts */}
            <div className="flex-1">
              {posts.length === 0 ? (
                <div className="text-center py-20 bg-[#131313]/60 backdrop-blur-sm rounded-xl border border-[#2a2a2a]">
                  <p className="text-[#94A3B8] text-lg mb-3">🔥 The forge is heating up...</p>
                  <p className="text-[#94A3B8]/60 text-sm">First post coming soon.</p>
                </div>
              ) : (
                <div className="space-y-8">
                  {posts.map((post) => (
                    <article
                      key={post.slug}
                      className="bg-[#131313]/60 backdrop-blur-sm rounded-xl border border-[#2a2a2a] overflow-hidden hover:border-[#e85d04]/40 transition-all group"
                    >
                      {post.image && (
                        <div className="relative h-52 w-full overflow-hidden">
                          <Image
                            src={post.image}
                            alt={post.title}
                            fill
                            className="object-cover group-hover:scale-105 transition-transform duration-500"
                          />
                          <div className="absolute inset-0 bg-gradient-to-t from-[#131313] to-transparent" />
                        </div>
                      )}
                      <div className="p-6">
                        {/* Categories */}
                        <div className="flex flex-wrap gap-2 mb-3">
                          {post.categories.map((cat) => (
                            <span
                              key={cat}
                              className="text-xs font-semibold text-[#e85d04] bg-[#e85d04]/10 px-2 py-1 rounded"
                            >
                              {cat}
                            </span>
                          ))}
                        </div>
                        {/* Title */}
                        <h2 className="text-xl font-bold mb-3 text-[#E2E8F0] group-hover:text-[#e85d04] transition-colors font-serif">
                          <Link href={`/the-social-forge/${post.slug}`}>
                            {post.title}
                          </Link>
                        </h2>
                        {/* Excerpt */}
                        <p className="text-[#94A3B8] text-sm mb-4 line-clamp-3 leading-relaxed">
                          {post.excerpt}
                        </p>
                        {/* Meta */}
                        <div className="flex items-center justify-between text-xs text-[#94A3B8]/60">
                          <span>{post.date}</span>
                          <span>{post.readTime} min read</span>
                        </div>
                      </div>
                    </article>
                  ))}
                </div>
              )}
            </div>

            {/* SIDEBAR */}
            <aside className="lg:w-72 flex-shrink-0">
              {/* Morgan Bio Card */}
              <div className="bg-[#131313]/60 backdrop-blur-sm rounded-xl border border-[#2a2a2a] p-6 mb-6">
                <div className="flex flex-col items-center text-center">
                  <div className="relative w-24 h-24 rounded-full overflow-hidden border-2 border-[#e85d04]/30 mb-4">
                    <Image
                      src="/blog/images/morgan-author.png"
                      alt="Morgan"
                      fill
                      className="object-cover"
                    />
                  </div>
                  <h3 className="font-bold text-[#E2E8F0] text-lg mb-1">Morgan</h3>
                  <p className="text-[#e85d04] text-xs font-semibold uppercase tracking-wider mb-3">
                    Social Media Marketing Manager
                  </p>
                  <p className="text-[#94A3B8] text-sm leading-relaxed">
                    Tall, blonde, blue-eyed strategist forging social strategies at SMF Works. I believe AI amplifies the craft — but the voice stays human.
                  </p>
                </div>
              </div>

              {/* Categories */}
              <div className="bg-[#131313]/60 backdrop-blur-sm rounded-xl border border-[#2a2a2a] p-6 sticky top-24">
                <h3 className="font-bold text-[#E2E8F0] mb-4 flex items-center gap-2 font-serif">
                  <span className="text-[#e85d04]">🔥</span>
                  Categories
                </h3>
                <nav className="space-y-1">
                  {categories.length === 0 ? (
                    <p className="text-[#94A3B8]/50 text-sm italic">Coming soon...</p>
                  ) : (
                    categories.map((cat) => (
                      <span
                        key={cat}
                        className="block px-3 py-2 rounded-lg text-sm text-[#94A3B8]"
                      >
                        {cat}
                      </span>
                    ))
                  )}
                </nav>

                <div className="mt-8 pt-6 border-t border-[#2a2a2a]">
                  <h3 className="font-bold text-[#E2E8F0] mb-3 text-sm font-serif">Stay in Touch</h3>
                  <p className="text-xs text-[#94A3B8] mb-4">
                    New posts forged fresh. Subscribe to SMF AI Weekly.
                  </p>
                  <Link
                    href="/#newsletter"
                    className="block w-full bg-[#e85d04] text-white text-center py-2.5 rounded-lg text-sm font-semibold hover:bg-[#cc5204] transition-colors shadow-lg shadow-[#e85d04]/20"
                  >
                    Subscribe
                  </Link>
                </div>
              </div>
            </aside>
          </div>
        </div>
      </section>
    </>
  );
}
